require('dotenv').config();
const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const authRoutes    = require('./routes/auth');
const messageRoutes = require('./routes/messages');
const logRoutes     = require('./routes/logs');
const { startScheduler } = require('./jobs/scheduler');
const app = express();
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:3000', credentials: true }));
app.use(express.json());
app.use(morgan('dev'));
app.use('/api/auth',     authRoutes);
app.use('/api/messages', messageRoutes);
app.use('/api/logs',     logRoutes);
app.get('/health', (_, res) => res.json({ status: 'ok', time: new Date() }));
app.use((req, res) => res.status(404).json({ error: `${req.method} ${req.path} not found` }));
app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: 'Internal server error' }); });
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => { console.log(`\n🚀 SmartMsg API → http://localhost:${PORT}`); startScheduler(); });
